/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as AuthenticatedLayoutAppRouteImport } from './routes/_authenticated/_layout/app'
import { Route as AuthenticatedLayoutParseJobIdRouteImport } from './routes/_authenticated/_layout/parse.$jobId'
import { Route as AuthenticatedLayoutExtractJobIdRouteImport } from './routes/_authenticated/_layout/extract.$jobId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLayoutAppRoute = AuthenticatedLayoutAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const AuthenticatedLayoutParseJobIdRoute =
  AuthenticatedLayoutParseJobIdRouteImport.update({
    id: '/parse/$jobId',
    path: '/parse/$jobId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutExtractJobIdRoute =
  AuthenticatedLayoutExtractJobIdRouteImport.update({
    id: '/extract/$jobId',
    path: '/extract/$jobId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthenticatedLayoutAppRoute
  '/extract/$jobId': typeof AuthenticatedLayoutExtractJobIdRoute
  '/parse/$jobId': typeof AuthenticatedLayoutParseJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthenticatedLayoutAppRoute
  '/extract/$jobId': typeof AuthenticatedLayoutExtractJobIdRoute
  '/parse/$jobId': typeof AuthenticatedLayoutParseJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/_layout/app': typeof AuthenticatedLayoutAppRoute
  '/_authenticated/_layout/extract/$jobId': typeof AuthenticatedLayoutExtractJobIdRoute
  '/_authenticated/_layout/parse/$jobId': typeof AuthenticatedLayoutParseJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/app' | '/extract/$jobId' | '/parse/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/app' | '/extract/$jobId' | '/parse/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_layout'
    | '/_authenticated/_layout/app'
    | '/_authenticated/_layout/extract/$jobId'
    | '/_authenticated/_layout/parse/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_layout/app': {
      id: '/_authenticated/_layout/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedLayoutAppRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/parse/$jobId': {
      id: '/_authenticated/_layout/parse/$jobId'
      path: '/parse/$jobId'
      fullPath: '/parse/$jobId'
      preLoaderRoute: typeof AuthenticatedLayoutParseJobIdRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/extract/$jobId': {
      id: '/_authenticated/_layout/extract/$jobId'
      path: '/extract/$jobId'
      fullPath: '/extract/$jobId'
      preLoaderRoute: typeof AuthenticatedLayoutExtractJobIdRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutAppRoute: typeof AuthenticatedLayoutAppRoute
  AuthenticatedLayoutExtractJobIdRoute: typeof AuthenticatedLayoutExtractJobIdRoute
  AuthenticatedLayoutParseJobIdRoute: typeof AuthenticatedLayoutParseJobIdRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutAppRoute: AuthenticatedLayoutAppRoute,
  AuthenticatedLayoutExtractJobIdRoute: AuthenticatedLayoutExtractJobIdRoute,
  AuthenticatedLayoutParseJobIdRoute: AuthenticatedLayoutParseJobIdRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
